
version: 2

models:
  - name: int_customers__assembly
    description: "Assemby of Customers from T_SAMPLE_DATASET and T_ECOMMERCE_CUSTOMER_DATA_CUSTOM_RATIOS"
    columns:
      - name: unique_raw_id
        data_tests:
          - unique
          - not_null
      - name: gender
        data_tests:
          - accepted_values:
              values: ['F', 'M', 'UNKNOWN']

  - name: int_products__assembly
    description: "Assemby of Products"
    columns:
      - name: unique_raw_id
        data_tests:
          - unique
          - not_null