name: DBT Tests & Merge

on:
  pull_request:
    branches:
      - master

jobs:
  dbt-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dbt and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-snowflake
        pip install -r requirements.txt

    - name: Set up Snowflake environment
      run: |
        mkdir -p ~/.dbt
        echo "dbt_sales_data_processing:" > ~/.dbt/profiles.yml
        echo "  target: dev" >> ~/.dbt/profiles.yml
        echo "  outputs:" >> ~/.dbt/profiles.yml
        echo "    dev:" >> ~/.dbt/profiles.yml
        echo "      type: snowflake" >> ~/.dbt/profiles.yml
        echo "      account: ${{ secrets.SNOWFLAKE_ACCOUNT }}" >> ~/.dbt/profiles.yml
        echo "      user: ${{ secrets.SNOWFLAKE_USER }}" >> ~/.dbt/profiles.yml
        echo "      password: ${{ secrets.SNOWFLAKE_PASSWORD }}" >> ~/.dbt/profiles.yml
        echo "      role: ${{ secrets.SNOWFLAKE_ROLE }}" >> ~/.dbt/profiles.yml
        echo "      database: ${{ secrets.SNOWFLAKE_DATABASE }}" >> ~/.dbt/profiles.yml
        echo "      warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}" >> ~/.dbt/profiles.yml
        echo "      schema: ${{ secrets.SNOWFLAKE_SCHEMA }}" >> ~/.dbt/profiles.yml
        echo "      threads: 1" >> ~/.dbt/profiles.yml

    - name: Run dbt tests
      run: |
        dbt deps  # Télécharger les dépendances dbt
        dbt seed  # (optionnel)
        dbt run   # Exécuter les modèles dbt
        dbt test  # Exécuter les tests dbt

  merge:
    needs: dbt-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Merge PR
      if: ${{ github.event.pull_request.merged == false }}
      run: |
        gh pr merge ${{ github.event.pull_request.number }} --merge --admin
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
