
version: 2

sources:
  - name: E_COMMERCE
    database: SALES_DATALAKE
    schema: E_COMMERCE
    tables:
      - name: T_SAMPLE_DATASET
      - name: T_SALES_DATA
      - name: T_CUSTOMER_CHURN_TESTING

models:
  - name: t_customers
    description: "A set of Customers extracted from raw sources"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
